ヘッダーとヒーローの作成
YuukiAkimoto/frontend-basic-site pull request #1
Opened 2024-04-06 01:00 UTC by YuukiAkimoto

2024-04-07 14:49 UTC, Riku-Obata requested changes
コメントしました！PC版の修正をお願いします。SP版は完璧でした！
1回目のレビューですが、しっかりと出来ていて素晴らしいと感じました！！
この調子で頑張ってください！

[おまけ]
この拡張機能おすすめです！
デザインデータを入れて、そのデータとコーディングがどれだけズレているのかを知ることができます。
積極的に使ってみることで、「Figma(デザイン)とのずれ」というのが分かるようになっていきます！
https://chrome.google.com/webstore/detail/perfectpixel-by-welldonec/dkaagdgjmgdmbnecmcefdhjekcoceebi?hl=ja

使い方等について書かれています。
https://webliker.info/html/pixel-perfect/
**上の拡張機能を使って、Headerの文字間隔をできるだけ近づけてみてください**

2024-04-07 14:49 UTC, Riku-Obata commented on style.css
> +    letter-spacing: 0.05rem;
```suggestion
    letter-spacing: 0.05em;
```
文字の間隔が少し狭いので、修正をお願いします

emとremについてまとめたサイトがあるので、参考程度に読むといいです！
https://www.pc-koubou.jp/magazine/23912

2024-04-07 14:49 UTC, Riku-Obata commented on style.css
> +}
背景の写真の位置がFigmaのお手本とずれているので、修正をお願いします
使うCSSは”background-positon:○○”です！！
（○○は自分で考えて入れてみてください）

2024-04-08 03:04 UTC, YuukiAkimoto commented on style.css
> +    letter-spacing: 0.05rem;
修正しました！

2024-04-08 03:04 UTC, YuukiAkimoto commented on style.css
> +}
修正しました！

2024-04-08 12:54 UTC, Riku-Obata commented
きちんと修正されていていいと思います！LGTM！

2024-04-10 17:05 UTC, ssshun3 commented on index.html
現在のコードではタグのインデントがそろっておらず可読性の面であまりいいとは言えません。
そのためコード整形ツールであるprettierを導入しましょう。以下の動画にあるPrettierの導入を確認してみてください。
https://shinonome-inc.notion.site/697a211574334d879cf467f0af501723

2024-04-10 17:05 UTC, ssshun3 commented on index.html
> +            <img class="header-logo" src="/img/logo.svg" alt="Grand Players"></h1>
画像のpathに関して絶対パスを採用されている理由などはございますか？
基本画像などを表示させる際、絶対パスだと開発環境とデプロイ環境の違いに影響されてしまうため、相対パスが推奨されています。
https://webukatu.com/wordpress/blog/3876/#i-4

2024-04-10 21:41 UTC, YuukiAkimoto commented on index.html
修正しました。

2024-04-10 21:41 UTC, YuukiAkimoto commented on index.html
> +            <img class="header-logo" src="/img/logo.svg" alt="Grand Players"></h1>
すみません。絶対パスを使っている所を自分には見つけることが出来ませんでした。
/img/logo.svgのところが絶対パスになっているのでしょうか？

2024-04-11 02:46 UTC, ssshun3 commented on index.html
> +        <img class="header-logo" src="/img/logo.svg" alt="Grand Players" />
> すみません。絶対パスを使っている所を自分には見つけることが出来ませんでした。 /img/logo.svgのところが絶対パスになっているのでしょうか？

そうです。相対パスで表すと以下のようになります。
```suggestion
        <img class="header-logo" src="./img/logo.svg" alt="Grand Players" />
```

2024-04-11 10:54 UTC, YuukiAkimoto commented on index.html
> +        <img class="header-logo" src="/img/logo.svg" alt="Grand Players" />
なるほど！！
理解しました！！！
修正しました！

2024-04-12 13:46 UTC, ssshun3 approved these changes
LGTM

2024-04-13 02:08 UTC, merged